### PR TITLE
Polymer-designer in a separate module

### PR DESCRIPTION
**Pull request by webdesus**
Good day. What do you think about  to make a polymer-designer in a separate module?

So will be able to at least use the editor how minimum in the following projects:
* **Chrome Dev Editor** (The chrome dev team will not have to write something of their own, they just Add a link in bower)
* **Polymer Desiner Online** (what now is)
* **Polymer Desiner Tool** (going to write a small tool that can be called from any code editor (Sublime, WebStorm, eclipse etc) and start editing the given file)
* **Fast Prototype** (Annex which is already a long time I think, and thanks to the polymer and the designer can see it very real. In fact, the designer, who must cope with not even a programmer. There used to be at Google had something like that in the script, by the way with the polymer-desinger this thing can be returned.)

  
I know that as long as you are not planning to develop polymer-designer, but while community can. Personally, I have a lot of ideas.The appearance of Polymer Designer Tool will attract more people to the project.

I work about 2 years team leader in c# and in this interested in a quick and easy creation of prototypes and applications facilitating life (see the tree in the database like total commander folder, what may be a macro to the interface)

I'm really bad composes proposals in English, and now I have tornado in my head from the opportunities polymer-designer. On this highlight like the following things

1. Polymers needed a designer for its promotion. I think people will come to this area for the designer, and then to understand what is the polymer and how they ever lived without it) For now, many dosih are skeptical about this project. Assuming that connect what may be the same js plugin.
2. And it is better to do a separate module to the designer can easily be used in other applications.

Actually the whole concept outlined above is implemented in this pool.

`components / polymer-designer / example.html` - standard use of lead designer without git

`index.html` - Polymer Desiner Online.

What do you think about this? I ready overwrite if needed.

### CODE REVIEW

**Comment by webdesus** [comment]
@googlebot I Signed CLA

**Comment by webdesus** [comment]
@googlebot I Signed CLA

**Comment by webdesus** [comment]
@googlebot I Signed CLA

**Comment by justinfagnani** [comment]
Hi, and thanks for your interest and enthusiasm! It looks like we share many of the same ideas and vision for Designer.

Our work on Designer has not stopped, in fact, we are working on a completely new rewrite of Designer that will be opened up very soon (it relied on a few small private repo's, which we're taking out). It's not as far along in term of features as the current Designer, but the foundation is being laid.

The architecture of the new Designer is more secure and more suitable for use as a component itself, or as a collection of individual elements, which seems like what you've done here.

I'm reluctant to make many more changes to the existing codebase because it's just not a good place to build on. I can let you know when we move over the new code.

**Comment by webdesus** [comment]
Thanks, @justinfagnani for the reply. I will look forward to the release of the new designer. Pity that it occur in  private repository.

**Pull request closed without merging**
